version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ideasoft123
            MYSQL_DATABASE: ideasoft

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"